vile:
  ignore: [
      ".build",
      "coverage",
      "node_modules",
      "lib",
      "tags",
      ".test",
      ".ctags",
      ".git",
      "circle.yml",
      ".editorconfig",
      ".eslintignore",
      ".eslintrc",
      ".fs-lint",
      ".jshintrc",
      ".jshintignore",
      ".gitignore",
      ".npmrc",
      "README.md",
      ".vile.yml",
      ".vilerc"
    ]

coverage:
  config:
    path: coverage/lcov.info

length:
  config:
    file: 150
    line: 80

depcheck:
  config:
    ignore_dev_deps: false
    ignore_dirs: [ ]
    ignore_deps: [ "@forthright/*" ]

license:
  config:
    allowed: [
      "MIT",
      "MIT License",
      "MIT AND JSON",
      "The MIT License",
      "MPL",
      "MPL-2.0",
      "Public Domain",
      "PSF",
      "BSD",
      "BSD-3-Clause",
      "BSD-2-Clause",
      "Unlicense",
      "Artistic-2.0",
      "ISC",
      "WTFPL",
      "Apache",
      "Apache-2.0",
      "Apache 2.0",
      "Apache*",
      "Apachev2",
      "WTFPL",
      "GPL"
    ]
