vile:
  ignore: [
      ".build",
      "coverage",
      "node_modules",
      "lib",
      "tags",
      ".test",
      ".ctags",
      "circle.yml",
      "coffeelint.json",
      ".editorconfig",
      ".eslintignore",
      ".eslintrc",
      ".fs-lint",
      ".gitignore",
      ".npmrc",
      "README.md",
      ".vile.yml",
      ".vilerc"
    ]

coverage:
  config:
    path: coverage/lcov.info

length:
  config:
    file: 250
    line: 80

depcheck:
  config:
    ignore_dev_deps: false
    ignore_dirs: []
    ignore_deps: [
        "sass-lint",
        "@forthright/*"
      ]

license:
  config: [
      "MPL-2.0",
      "MIT",
      "MIT*",
      "The MIT License",
      "Public Domain",
      "PSF",
      "BSD",
      "BSD*",
      "BSD-3-Clause",
      "BSD-2-Clause",
      "BSD-3-Clause AND MIT",
      "Artistic-2.0",
      "(BSD-2-Clause OR MIT OR Apache-2.0)",
      "ISC",
      "WTFPL",
      "(BSD-2-Clause OR WTFPL)",
      "Apache*",
      "Apache License 2.0",
      "Apache 2.0",
      "Apache-2.0",
      "WTFPL"
    ]
