vile:
  ignore:
    - bin
    - LICENSE
    - appveyor.yml
    - coverage
    - coffeelint.json
    - .babelrc
    - .npmignore
    - .travis.yml
    - node_modules
    - .nyc_output
    - lib
    - tags
    - .git
    - .gitattributes
    - circle.yml
    - .editorconfig
    - .eslintignore
    - .eslintrc
    - .gitignore
    - .npmrc
    - README.md
    - .vile.yml

depcheck:
  config:
    ignore_dev_deps: true
    ignore_dirs:
      - src
      - test
      - node_modules
      - coverage

coverage:
  config:
    path: coverage/lcov.info
